# Generated by Django 3.0.6 on 2020-07-09 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='poster',
            new_name='username',
        ),
    ]
