# Generated by Django 3.0.6 on 2020-07-10 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20200709_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='followers',
            new_name='num_followers',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='following',
            new_name='num_following',
        ),
    ]
