# Generated by Django 3.0.6 on 2020-07-10 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20200709_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_followed', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.List_Follow'),
        ),
    ]
