# Generated by Django 3.0.6 on 2020-07-16 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='logged_user',
        ),
    ]
