# Generated by Django 3.0.6 on 2020-07-16 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_auto_20200716_0155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='logged_user',
            new_name='user',
        ),
    ]
