# Generated by Django 3.0.6 on 2020-07-17 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_post_followed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='followed',
        ),
    ]
